SET NAMES utf8mb4;
SET time_zone = '+08:00';
USE rent_seeking_analysis;

INSERT INTO sys_dict (dict_type, item_code, item_name, sort_order, enabled)
VALUES
  ('REGULATION_TYPE', 'POLICY', '政策类', 10, 1),
  ('REGULATION_TYPE', 'PROCEDURE', '流程类', 20, 1),
  ('REGULATION_TYPE', 'APPROVAL', '审批类', 30, 1),
  ('REGULATION_TYPE', 'SUPERVISION', '监督类', 40, 1),
  ('REGULATION_STATUS', 'DRAFT', '草稿', 10, 1),
  ('REGULATION_STATUS', 'ACTIVE', '已生效', 20, 1),
  ('REGULATION_STATUS', 'INACTIVE', '已失效', 30, 1),
  ('REGULATION_STATUS', 'ARCHIVED', '已归档', 40, 1),
  ('RISK_LEVEL', 'LOW', '低风险', 10, 1),
  ('RISK_LEVEL', 'MEDIUM', '中风险', 20, 1),
  ('RISK_LEVEL', 'HIGH', '高风险', 30, 1),
  ('RISK_LEVEL', 'CRITICAL', '严重风险', 40, 1),
  ('RISK_ANALYSIS_STATUS', 'NOT_ANALYZED', '未分析', 10, 1),
  ('RISK_ANALYSIS_STATUS', 'ANALYZING', '分析中', 20, 1),
  ('RISK_ANALYSIS_STATUS', 'COMPLETED', '已完成', 30, 1),
  ('RISK_ANALYSIS_STATUS', 'FAILED', '分析失败', 40, 1),
  ('RISK_REVIEW_STATUS', 'PENDING', '待复核', 10, 1),
  ('RISK_REVIEW_STATUS', 'CONFIRMED', '已确认', 20, 1),
  ('RISK_REVIEW_STATUS', 'ADJUSTED', '已调整', 30, 1),
  ('RISK_INDICATOR', 'DISCRETIONARY_POWER', '自由裁量权', 10, 1),
  ('RISK_INDICATOR', 'APPROVAL_CONCENTRATION', '审批集中度', 20, 1),
  ('RISK_INDICATOR', 'PROCESS_TRANSPARENCY', '流程透明度', 30, 1),
  ('RISK_INDICATOR', 'SUPERVISION_CONSTRAINT', '监督约束', 40, 1),
  ('RISK_INDICATOR', 'BENEFIT_RELATED', '利益关联', 50, 1),
  ('RISK_INDICATOR', 'PENALTY_FLEXIBILITY', '处罚弹性', 60, 1),
  ('RISK_INDICATOR', 'TIME_WINDOW_RENT', '时间窗口寻租', 70, 1),
  ('CONFLICT_TYPE', 'DUPLICATE', '重复', 10, 1),
  ('CONFLICT_TYPE', 'INCONSISTENT', '不一致', 20, 1),
  ('CONFLICT_TYPE', 'SCOPE_CONFLICT', '适用范围冲突', 30, 1),
  ('CONFLICT_TYPE', 'SUBJECT_CONFLICT', '主体冲突', 40, 1),
  ('CONFLICT_TYPE', 'TIME_CONFLICT', '时间冲突', 50, 1),
  ('CONFLICT_LEVEL', 'LOW', '低', 10, 1),
  ('CONFLICT_LEVEL', 'MEDIUM', '中', 20, 1),
  ('CONFLICT_LEVEL', 'HIGH', '高', 30, 1),
  ('CONFLICT_LEVEL', 'CRITICAL', '严重', 40, 1),
  ('CONFLICT_STATUS', 'PENDING', '待确认', 10, 1),
  ('CONFLICT_STATUS', 'CONFIRMED', '已确认', 20, 1),
  ('CONFLICT_STATUS', 'IGNORED', '已忽略', 30, 1),
  ('TASK_STATUS', 'PENDING', '待处理', 10, 1),
  ('TASK_STATUS', 'RUNNING', '执行中', 20, 1),
  ('TASK_STATUS', 'COMPLETED', '已完成', 30, 1),
  ('TASK_STATUS', 'FAILED', '失败', 40, 1),
  ('AI_SCENE', 'REGULATION_SUMMARY', '制度摘要', 10, 1),
  ('AI_SCENE', 'CONFLICT_EXPLANATION', '冲突说明', 20, 1),
  ('AI_SCENE', 'RENT_SEEKING_RISK', '寻租风险识别', 30, 1),
  ('AI_SCENE', 'RECTIFICATION_SUGGESTION', '整改建议', 40, 1),
  ('AI_SCENE', 'REPORT_GENERATION', '报告生成', 50, 1),
  ('AI_SCENE', 'REGULATION_QA', '单项制度问答', 60, 1),
  ('AI_SCENE', 'CASE_RENT_SEEKING_ANALYSIS', '案例扩展寻租分析', 70, 1),
  ('AI_RECORD_STATUS', 'SUCCESS', '成功', 10, 1),
  ('AI_RECORD_STATUS', 'FAILED', '失败', 20, 1),
  ('USER_STATUS', 'ENABLED', '启用', 10, 1),
  ('USER_STATUS', 'DISABLED', '禁用', 20, 1),
  ('USER_STATUS', 'LOCKED', '锁定', 30, 1)
ON DUPLICATE KEY UPDATE
  item_name = VALUES(item_name),
  sort_order = VALUES(sort_order),
  enabled = VALUES(enabled);
